version: '3.8'

services:
  postgres:
    image: postgres
    restart: always
    env_file:
      - .test.env
    environment:
      POSTGRES_USER: ${POSTGRESQL_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
      POSTGRES_DB: ${POSTGRESQL_DB}
    ports:
      - ${POSTGRESQL_PORT}:${POSTGRESQL_PORT}
